---
dependency:
  name: galaxy

lint: |
  set -e
  yamllint .
  ansible-lint

platforms:
  - name: myapache
    image: "geerlingguy/docker-ubuntu2004-ansible"
    command: ""
    pre_build_image: true

provisioner:
  name: ansible

verifier:
  name: ansible
